version: '3'

services:
  aggregator:
    container_name: aggregator
    image: aggregator-service
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run start
    restart: always
    ports:
      - 3000:3000