version: '3'

services:
  reward-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d